#!/usr/bin/perl
#-----------------------------------------------------------------------------
# Copyright (C)1999 InfoStreet, Inc.    www.infostreet.com
# 
# Author:   Laurentiu C. Badea (L.C.) sourceforge.net/users/wotevah
# Created:  1999
# $LastChangedDate$
# $LastChangedBy$
# $Revision$
#
# Description:
# Generate a C source file mapping signal numbers to their names
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# Version 2, as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to:
# Free Software Foundation, Inc. 
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
#-----------------------------------------------------------------------------

open( GCC, "gcc -E -dM /usr/include/signal.h |" )
  or die "Can't run gcc!\n";
while (<GCC>){
  if (/#define (SIG[A-Z]+) (\d+)/o){ 
    $sig[$2] = $1 if ($2 < 64); 
  }; 
}
print "/* Generated by $0 */\n\n";
print "char *SIGNAL_NAMES[] = {\n";
for $i ( 0..$#sig ){ 
  print "\t". ( ($sig[$i]) ? "\"$sig[$i]\"" : "\"$i\"" ); 
  print "," if ($i < $#sig);
  print "\n";
};
print "};

char *SIGNAL_NAME(int sig){
  return (sig <= $#sig && sig >= 0) ? SIGNAL_NAMES[sig] : \"???\";
}

";

